All the code
rodsouza9/sudko pull request #2
Opened 2019-12-31 22:07 UTC by rodsouza9

Review for all the code

2019-12-31 23:14 UTC, advait requested changes

2019-12-31 23:14 UTC, advait commented on src/App.css
> +    align-items: center;
Get a linter that automatically sorts css properties in alpha order.

2019-12-31 23:14 UTC, advait commented on src/App.tsx
> +    permanentValues: SquareAddress[];
These might be better represented as `Set`s: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

2019-12-31 23:14 UTC, advait commented on src/App.tsx
> +        values: this.props.values,
Hard rule: Do not ever set state values based on prop values.

Remove the `values` key.

2019-12-31 23:14 UTC, advait commented on src/App.tsx
> +    public getPermanentValues(): SquareAddress[] {
What is this function for?

2019-12-31 23:14 UTC, advait commented on src/App.tsx
> +        this.state.permanentValues = this.getPermanentValues();
Rule: Don't ever set state via `this.state.foo = bar`. Always call `setState`.

Rule: Don't ever call `setState` in `render`

2019-12-31 23:14 UTC, advait commented on src/App.tsx
> +/*     convertUndefinedValues(): (SquareValue | null)[] {
Commented code should not be committed. Delete it and refer to the commit history to retrieve it.

2019-12-31 23:14 UTC, advait commented on src/App.tsx
> +        this.setState({
You are blowing away other parts of the state.

Add a `...this.state` before `values`

2019-12-31 23:14 UTC, advait commented on src/App.tsx
> +    public deleteSelectedSquares(): void {
Please add a jsdoc comment explaining what this function is supposed to do.

2019-12-31 23:14 UTC, advait commented on src/App.tsx
> +        return <Square value={this.state.values[i]}
This line is too long. Please add a newline for each prop.

2019-12-31 23:14 UTC, advait commented on src/App.tsx
> +    public getMarks(): boolean[] {
Please rewrite this as:

```js
public isMarked(squareValue: SquareValue): boolean
```

2019-12-31 23:14 UTC, advait commented on src/App.tsx
> +                    <div className="mark">{marks[1] ? 1 : null}</div>
Replace these with a loop

2019-12-31 23:14 UTC, advait commented on src/App.tsx
> +        const displayMarkings: (boolean | 0) = // determine if markings or value should be displayed
`boolean | 0` is an inappropriate type. Please use `boolean`.

2019-12-31 23:14 UTC, advait commented on src/App.tsx
> +            this.props.markings && this.props.markings.length &&
Please add a newline for each `&&`

2019-12-31 23:14 UTC, advait commented on src/App.tsx
> +class NormalButton extends React.Component<{}, {}> {
Please inline these four classes.

Inline means don't create separate classes for each of these.

2019-12-31 23:14 UTC, advait commented on src/App.tsx
> +            const addy: SquareAddress = this.state.highlights[j];
`address`

2019-12-31 23:14 UTC, advait commented on src/App.tsx
> +                this.setState({
`...this.state`.

2020-01-01 00:30 UTC, rodsouza9 commented on src/App.tsx
> +        values: this.props.values,
I need a value key that represents all the values in reach square in the board component. But the permanent values are going to be passed in by the prop. So should I just initially set values to [] and then create a function called setValues() which reads the prop and copies the permanent values into the correct positions? and then call that function in the render() of the board. This is how I did the permanentValues key

2020-01-01 19:50 UTC, advait commented on src/App.tsx
> +                    <div className="mark">{marks[1] ? 1 : null}</div>
Use the `.map` method on Arrays:
https://alligator.io/react/rendering-arrays-in-react/

2020-01-01 19:51 UTC, advait commented on src/App.tsx
> +    public getMarks(): boolean[] {
On second thought, maybe replace with a `renderMarking(squareValue: SquareValue)` method.

2020-01-01 22:36 UTC, advait requested changes
Code is looking a lot better! Minor comments.

2020-01-01 22:36 UTC, advait commented on src/App.tsx
> +            isHighlighted = {isHighlighted}
Whitespace

2020-01-01 22:36 UTC, advait commented on src/App.tsx
> +    public renderMarkings() {
Collapse the functionality of getMarks and rederMarkings into a single function.

2020-01-01 22:36 UTC, advait commented on src/App.tsx
> +    public render() {
New line

2020-01-01 22:36 UTC, advait commented on src/App.tsx
> +            this.props.markings &&
This check is unnecessary, no?

2020-01-01 22:49 UTC, merged